extends:
  - 'plugin:@ianwremmel/ianwremmel/node'
overrides:
  - env:
      mocha: true
    files:
      - '**/*-spec.js'
      - 'test/**/*'
    rules:
      max-nested-callbacks: off
      require-jsdoc: off
parserOptions:
  sourceType: 'script'
rules:
  class-methods-use-this: off
